galaxy_info:
  author: Suzuki Shunsuke
  description: Install Docker CE on CentOS
  license: MIT
  min_ansible_version: 1.2
  github_branch: master

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
  - docker

dependencies: []
