---
# tasks file for ansible_role_kubernetes_slave
  - debug:
      msg: "{{ k8s_cluster_token }}"

  - debug:
      msg: "{{ k8s_master_node }}"
      
  - fail:
      msg: "Bailing out. this role needs the cluster token"
    when: k8s_cluster_token is not defined

  - include: RedHat/main.yml
    when: ansible_os_family == "RedHat"

  - include: join.yml
