---

- name: install_docker.yml | All roles
  hosts: install_docker
  become: True

  roles:
    - { role: ansible-hostname,            tags: ["hostname"] }
    - { role: ansible-changeyumrepos,      tags: ["changeyumrepos"] }
    - { role: ansible-system-prepare,      tags: ["system-prepare"] }
    - { role: ansible-docker,            tags: ["docker"] }
    - { role: ansible-dockerimg-accelerate,            tags: ["dockerimg-accelerate"] }